export const UPDATE = 'UPDATE';
export const CREATE = 'CREATE';
export const DELETE = 'DELETE';
export const FETCH_ALL = 'FETCH_ALL';
export const FETCH_PENDING = 'FETCH_PENDING';
export const LIKE = 'LIKE';
export const QUERY = 'QUERY';
export const FETCH_ALL_CAUSE_LIST = 'FETCH_ALL_CAUSE_LIST';
export const CREATE_CONTROL_CENTER = 'CREATE_CONTROL_CENTER';
export const FETCH_ALL_CONTROL_CENTER = 'FETCH_ALL_CONTROL_CENTER';

export const FETCH_ALL_EMPLOYEE_DATA = 'FETCH_ALL_EMPLOYEE_DATA';